### ISSUE TITLE
Thanks for your work

### ISSUE THREAD

**Issue by florentdupont** [lynas/spring-security-jwt-rest-stateless#3]
For information, I re-created a new repository based from yours. Not a fork but a new one.

it's available [here](https://github.com/SNCF-SIV/spring-security-rest-jwt).
I made some changes : 
- Replacing Gradle to Maven
- Replacing MySQL to MongoDB
- Some minor changes (package names)
- Spring Security configuration has been corrected
- library versions updated (to conform to those of Spring Boot 1.4)
- Correcting the filter chain
- The token is not revalidated against database each time
- No _refresh token_ functionality here
- Moving to [Nimbus JOSE JWT](http://connect2id.com/products/nimbus-jose-jwt) implementation.
- Correcting README

Thanks again for your work, it helped me a lot !!

**Comment by lynas** [comment]
You are most welcome
