### ISSUE TITLE
Did you test the endpoints with authorities?

### ISSUE THREAD

**Issue by gdiazs** [lynas/spring-security-jwt-rest-stateless#4]
Thanks for your example! Very Usefull.

Hi I have some problems with authorization. I did a diferent configuration. I move the security to a maven module, and then later in the web project  I scan all components that security needs, like DAO, Services and Auth controller, but when I preauthorize the endpoints with some authority wrong, the controller response the entity anyway. 

Do you have similar problem?

**Comment by lynas** [comment]
No I did not face any problem like that
